services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    privileged: true
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


  psyche:
    image: adijida/psyche:latest
    #image: psyche
    container_name: psyche-api
    restart: always
    depends_on:
      - ollama
    env_file:
      - .env

volumes:
  ollama-data: